name: efl_mobile
description: eFootball League Mobile App - Connect to the professional eFootball gaming ecosystem
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Network & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # WebSockets
  web_socket_channel: ^2.4.0
  socket_io_client: ^2.0.3+1
  
  # Storage & Cache
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Video Player
  video_player: ^2.8.1
  chewie: ^1.7.5
  
  # Image Picker & Upload
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  
  # Date & Time
  intl: ^0.18.1
  timeago: ^3.6.0
  
  # Utilities
  logger: ^2.0.2+1
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  
  # Animations
  lottie: ^3.0.0
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/animations/
    - assets/icons/
  
  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf
          weight: 700
        - asset: assets/fonts/Orbitron-Black.ttf
          weight: 900
